# Generated by Django 3.1.2 on 2020-10-21 01:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address_line1', models.CharField(max_length=255)),
                ('address_line2', models.CharField(blank=True, max_length=255, null=True)),
                ('zipCode', models.PositiveIntegerField(blank=True)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('country', models.CharField(blank=True, max_length=100)),
                ('title', models.CharField(max_length=255)),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('description', models.TextField(blank=True, null=True)),
                ('category', models.CharField(choices=[('Business/Professional', 'Business Or Professional'), ('Charity/Causes', 'Charity Or Causes'), ('Community/Culture', 'Community Or Culture'), ('Education', 'Education'), ('Fashion/Beauty', 'Fashion And Beauty'), ('Entertainment/Media', 'Entertainment Media Film'), ('Government/Politics', 'Government Or Politics'), ('Health/Wellness', 'Health And Wellness'), ('Lifestyle', 'Lifestyle'), ('Music', 'Music'), ('Religion/Spirituality', 'Religion Or Spirituality'), ('Science/Tech', 'Science And Tech'), ('Sport/Fitness', 'Sport And Fitness'), ('Travel/Outdoor', 'Travel Or Outdoor'), ('Party', 'Party'), ('Other', 'Other')], max_length=30)),
                ('status', models.CharField(choices=[('Published', 'Published'), ('Past', 'Past'), ('Draft', 'Draft')], default='Draft', max_length=10)),
                ('open_slots_left', models.IntegerField()),
                ('organizer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='EventRegistration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registration_date', models.DateTimeField(auto_now=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='event.event')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
