# Generated by Django 3.1.2 on 2020-10-22 22:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('event', '0002_auto_20201022_0128'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='open_slots_left',
            new_name='max_attendees',
        ),
        migrations.AddField(
            model_name='event',
            name='num_of_registered',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
